### ISSUE TITLE
[1.10.2] Error in console

### ISSUE THREAD

**Issue by MJRLegends** [coolsquid/PackGuard#1]
Error: https://pastebin.com/0h5EA9jd

PackGuard-1.10.2-2.2.0.jar

**Comment by coolsquid** [comment]
This should be harmless, it's just a leftover from 1.7. If everything loads fine, you can just ignore it. I'll see if I can push a fix in a week or two.

**Comment by MJRLegends** [comment]
Yeah, but thought i'd mention it, its nothing major so take as long as you need :D

**Comment by MJRLegends** [comment]
Thanks for the release with this fixed :D
